language: node_js
node_js:
  - "6"
sudo: required
services:
  - docker

before_install:
  - sudo apt remove docker
  - curl -fsSL https://get.docker.com/ | sh > /dev/null
  
before_script:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install -g gulp


script:
 - gulp test:all-non-e2e
 - gulp coverage
 - gulp test:protractor
