version: '2.0'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO: 'mongodb://mongo/Scraaam'
